######################################################################
# Automatically generated by qmake (3.0) Sat Jul 23 14:28:38 2016
######################################################################

TARGET = libavoid
INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

HEADERS += $$PWD/*.h
SOURCES += $$PWD/*.cpp
HEADERS += $$PWD/libavoid/*.h
SOURCES += $$PWD/libavoid/*.cpp
